services:
  ytm-jam-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ytm-jam-server
    environment:
      - PORT=3000
      - NODE_ENV=production
    ports:
      - "3000:3000"
    restart: unless-stopped
